default:
	@just --list
run:
	clear
	docker compose up --build
releaset tag="latest":
	clear
	docker login
	docker build -t "hadesmonsta/feedback_backend:{{tag}}" ./
	docker push "hadesmonsta/feedback_backend:{{tag}}"
release tag:
	clear
	just releaset "{{tag}}"
	just releaset
