default:
	@just --list
run:
	clear
	docker compose up --build
release tag:
	clear
	docker login
	docker build -t "hadesmonsta/feedback_review_backend:{{tag}}" ./
	docker push "hadesmonsta/feedback_review_backend:{{tag}}"
	docker build -t "hadesmonsta/feedback_review_backend:latest" ./
	docker push "hadesmonsta/feedback_review_backend:latest"

