[package]
name = "feedback_input"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0-rc.4"
rocket_contrib = "0.4.10"
urlencoding = "2.1.3"
dotenv = "0.15.0"
chrono = "0.4.34"
logger_utc = "0.1.1"
