[package]
name = "feedback_input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.4"
rocket_contrib = "0.4.10"
urlencoding = "2.1.3"
dotenv = "0.15.0"
chrono = "0.4.34"
