[package]
name = "feedback_input"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
urlencoding = "2.1.3"
dotenv = "0.15.0"
logger_utc = "0.2.0"
tonic = "0.11.0"
prost = "0.12.6"
tokio = {version = "1.38.0", features = ["macros", "rt-multi-thread"]}
rand = "0.9.0-alpha.1"

[build-dependencies]
tonic-build = "0.11.0"
