[package]
name = "feedback_input"
version = "0.1.1"
edition = "2021"

[features]
deutschland = []

# cargo build
[[bin]]
name = "feedback_input"
path = "src/main.rs"

# cargo build --features deutschland --bin DEUTSCHLAND
# Do not build both with `cargo build --features deutschland`
[[bin]]
name = "DEUTSCHLAND"
path = "src/main.rs"
required-features = ["deutschland"]

# Explanation: Cargo tries to build all target when no `--bin` is specified
# Without the feature we cannot build DEUTSCHLAND
# But with the features both will be built, which would activate the feature in both bins, what we don't want

[dependencies]
rocket = "0.5.1"
urlencoding = "2.1.3"
dotenv = "0.15.0"
logger_utc = "0.2.0"
tonic = "0.12.0"
prost = "0.13.1"
tokio = {version = "1.38.0", features = ["macros", "rt-multi-thread"]}
rand = "0.9.0-alpha.1"

[build-dependencies]
tonic-build = "0.12.0"
