[package]
name = "feedback_input"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.4"
rocket_contrib = "0.4.10"
protobuf = "3.3.0"
bytes = "1.0"
tokio = { version = "1", features = ["full"] }
tonic = "0.11.0"
urlencoding = "2.1.3"

[build-dependencies]
prost-build = "0.12.3"
prost-types = "0.12.3"
prost-derive = "0.12.3"
tonic-build = "0.11"
