services:
  feedback_input:
    image: hadesmonsta/feedback_input
    container_name: feedback_input
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./logs:/logs
    env_file:
      - .env
