run:
    cargo run --bin feedback_input
run_de:
    cargo run --bin DEUTSCHLAND --features deutschland
build:
    cargo build --bin feedback_input
clean:
    cargo clean
release:
    cargo build --bin feedback_input --release
deutschland:
    cargo build --bin DEUTSCHLAND --features deutschland --release
