target := "x86_64-unknown-linux-musl"
de := "deutschland"

run:
	cargo run
run_de:
	cargo run --features {{de}}
build:
	cargo build
clean:
	cargo clean
release:
	cargo build --release --target {{target}}
deutschland:
	cargo build --features {{de}} --release --target {{target}}
