[package]
name = "feedback_input_yew"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
wasm-bindgen = "0.2.100"
wasm-bindgen-futures = "0.4.50"
reqwest-wasm = "0.11.16"
anyhow = "1.0.97"
serde_json = "1.0.140"
