default:
	@just --list
clear:
	clear
dev: clear
	docker compose up --build
release tag: clear
	docker login
	docker build \
		-t "hadesmonsta/feedback_review:{{tag}}" \
		-t "hadesmonsta/feedback_review:latest" \
		./
	docker push "hadesmonsta/feedback_review:{{tag}}"
	docker push "hadesmonsta/feedback_review:latest"
